os:
  - osx
  - linux
dist: 
  - trusty
language: node_js
yarn: 1.6.0
node_js: 8.0.0
go: 1.10.0
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
